chore reworking updatecli manifest
jenkins-infra/docker-openvpn pull request #139
Opened 2022-02-21 16:26 UTC by smerle33

upgrading manifest to be compliant with new scm formating

2022-02-21 17:51 UTC, dduportal requested changes
Blocking the PR: as seen together, we have to update the behavior of the `parallelDockerUpdatecli()` shared library (https://github.com/jenkins-infra/pipeline-library/blob/master/vars/parallelDockerUpdatecli.groovy) to allow passing the docker image to the underlying `updatecli()` library, so we can use the same trick as in https://github.com/jenkins-infra/shared-tools/pull/2 to specify a custom Docker image with both Golang AND updatecli within

2022-02-22 10:35 UTC, dduportal commented
Depends on https://github.com/jenkins-infra/pipeline-library/pull/306

2022-02-22 11:37 UTC, lemeurherve commented on updatecli/updatecli.d/golang.yaml
> +
```suggestion
    scmID: default
```

2022-02-22 11:37 UTC, lemeurherve commented on updatecli/updatecli.d/golang.yaml
> +
(Ending line without an empty one after)

2022-02-23 07:38 UTC, dduportal approved these changes
LGTM (check is failing, updatecli diff 🥚 / 🐔 as usual)

2022-02-23 07:39 UTC, merged